apiVersion: batch/v1
kind: Job
metadata:
  name: secret-sync-controller
spec:
  template:
    spec:
      serviceAccountName: secret-sync-controller
      volumes:
      - name: config-volume
        configMap:
          name: config
      containers:
      - name: sync-container
        image: gcr.io/k8s-jkns-gke-soak/secret-sync-controller:latest
        command: 
        - sh
        args:
        - -c
        - |
          go build -o secret-sync-controller cmd/secret-sync-controller/main.go
          ./secret-sync-controller --config-path /tmp/config/syncConfig --period 1000
        volumeMounts:
        - name: config-volume
          readOnly: true
          mountPath: /tmp/config
      restartPolicy: Never