apiVersion: batch/v1
kind: Job
metadata:
  name: secret-sync-controller-test
spec:
  template:
    spec:
      serviceAccountName: secret-sync-controller
      volumes:
      - name: config-volume
        configMap:
          name: config
      containers:
      - name: sync-container
        image: gcr.io/k8s-jkns-gke-soak/secret-sync-controller:latest
        command: 
        - sh
        args:
        - -c
        - |
          go test ./...
          cd secret-sync-controller/controller
          go test -v --e2e-client --gsm-project=k8s-jkns-gke-soak
        volumeMounts:
        - name: config-volume
          readOnly: true
          mountPath: /tmp/config
      restartPolicy: Never